-- create table todos (
--   id bigint generated by default as identity primary key,
--   user_id uuid references auth.users not null,
--   task text check (char_length(task) > 3),
--   is_complete boolean default false,
--   inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
-- );
-- alter table todos enable row level security;
-- create policy "Individuals can create todos." on todos for
--     insert with check (auth.uid() = user_id);
-- create policy "Individuals can view their own todos. " on todos for
--     select using (auth.uid() = user_id);
-- create policy "Individuals can update their own todos." on todos for
--     update using (auth.uid() = user_id);
-- create policy "Individuals can delete their own todos." on todos for
--     delete using (auth.uid() = user_id);

-- Create the "ingredients" table
CREATE TABLE ingredients (
  id BIGSERIAL PRIMARY KEY,
  ingredient_name TEXT NOT NULL,
  benefit TEXT,
  risks TEXT,
  easily_grown BOOLEAN DEFAULT false,
  user_id UUID NOT NULL
);

-- Enable row-level security for the "ingredients" table
ALTER TABLE ingredients ENABLE ROW LEVEL SECURITY;

-- Create policies for the "ingredients" table
CREATE POLICY "Individuals can create ingredients." ON ingredients
  FOR INSERT
  WITH CHECK (TRUE);

CREATE POLICY "Individuals can view their own ingredients." ON ingredients
  FOR SELECT
  USING (auth.uid() = user_id);

-- Allow individuals to view all ingredients
CREATE POLICY "Individuals can view all ingredients." ON ingredients
  FOR SELECT
  USING (TRUE);

CREATE POLICY "Individuals can update their own ingredients." ON ingredients
  FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Individuals can delete their own ingredients." ON ingredients
  FOR DELETE
  USING (auth.uid() = user_id);